### ISSUE TITLE
shadowThemeOnly not founded

### ISSUE THREAD

**Issue by mustafa-fahimi** [whatamelon/flutter_dropdown_below#1]
When I use this library, I get this error.

> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_below-0.0.5/lib/dropdown_below.dart:543:32: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(context, shadowThemeOnly: true),
                               ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/theme.dart:106:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^

**Comment by whatamelon** [comment]
Hi @Tokenizer94, thx for use this package.
I'm already fixed this issue in version 0.0.6
Try install version 0.0.6 and issue is gone, than you can close this issue Thx XD!

**Comment by mustafa-fahimi** [comment]
Thanks.
