### ISSUE TITLE
Changing color and style of the box

### ISSUE THREAD

**Issue by ArefMozafari** [whatamelon/flutter_dropdown_below#2]
Hi
How can i change box style, icon, color and remove this white border?
![Screenshot 2021-05-30 170815](https://user-images.githubusercontent.com/29792606/120104440-a510ca80-c169-11eb-8482-19d1095d4fd5.png)

**Comment by whatamelon** [comment]
@ArefMozafari  Hi! Sadly, Box Style, Icon Color and border color is not customizable at this version.
So, you can customize it yourself by get cursor to this widget and press command + b, then you can enter this library.
And, you can customize it yourself.
Nowadays I'm not using flutter for my main skill. So, I wish I will upgrade this library asap.

**Comment by ArefMozafari** [comment]
I understand, thank you

**Comment by whatamelon** [comment]
@ArefMozafari 0.0.8ver is now release! You can test and close whenever you want.

**Comment by ArefMozafari** [comment]
Great job, thanks
